// Generated by ReScript, PLEASE EDIT WITH CARE

import * as More$MyNamespace from "./More.res.js";
import * as Other$MyNamespace from "./Other.res.js";
import * as JsxRuntime from "react/jsx-runtime";

let x = {
  a: 3
};

let l = (More$MyNamespace.inner + More$MyNamespace.n | 0) + Other$MyNamespace.inner | 0;

let me = {
  TAG: "People",
  _0: "Hie"
};

let x$1 = Other$MyNamespace.something + 10 | 0;

let Something_m = {
  name: "Me",
  age: 0
};

let Something_animal = {
  TAG: "Things",
  _0: 10
};

let Something_other = {
  TAG: "Things",
  _0: 2
};

let Something = {
  m: Something_m,
  animal: Something_animal,
  other: Something_other,
  me: me,
  x: x$1,
  r: "Me",
  awesome: 20
};

let aThing = 10 + Other$MyNamespace.something | 0;

function transform(x, y) {
  return x + y.toString();
}

transform("hello ", 5);

let added = 110;

let a_1 = {
  hd: "my finefolks",
  tl: {
    hd: "in boonville",
    tl: /* [] */0
  }
};

let a = {
  hd: "hello",
  tl: a_1
};

function div(x, y, children, param) {
  return 10;
}

JsxRuntime.jsx("div", {
  x: "10",
  y: "20"
});

function something(animal) {
  
}

function someFunction(memorableName, param) {
  return memorableName + 20 | 0;
}

for (let _index = 0; _index <= 10; ++_index) {
  console.log("hellO");
}

let TwoTwoTwoTwo = {
  xxxxxxxxxx: 10
};

let OneOneOneOne = {
  TwoTwoTwoTwo: TwoTwoTwoTwo
};

let y = 15;

let z = {
  contents: 30
};

function thing() {
  return 77;
}

let contents = z.contents;

let someLongName = 10;

let otherLongName = "string";

let zzz = 1;

let more = 20;

let m = Other$MyNamespace.later;

let r = 10;

let xxxxxxxxxx = 10;

let contnets = More$MyNamespace.contnets;

let inner = More$MyNamespace.inner;

let n = More$MyNamespace.n;

let party = {
  one: "one",
  two: 2
};

let one = "one";

let two = 2;

let awesome = "hello";

export {
  someLongName,
  otherLongName,
  x,
  l,
  Something,
  aThing,
  transform,
  zzz,
  more,
  added,
  a,
  div,
  something,
  someFunction,
  m,
  OneOneOneOne,
  r,
  xxxxxxxxxx,
  contnets,
  inner,
  n,
  y,
  z,
  party,
  one,
  two,
  thing,
  contents,
  awesome,
}
/*  Not a pure module */
