// Generated by ReScript, PLEASE EDIT WITH CARE


let z = {
  name: "hi",
  age: 20
};

function concat(first, second) {
  return first + second | 0;
}

let oo = {
  person: z,
  height: 34.2
};

function show(o) {
  
}

let something = 10;

let inner = 10;

let m = {
  TAG: "Things",
  _0: 1
};

let later = 20;

export {
  something,
  inner,
  m,
  z,
  later,
  concat,
  oo,
  show,
}
/* No side effect */
