// Generated by ReScript, PLEASE EDIT WITH CARE


function deserialize_Belt__HashMapInt__t(transformer, t) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "TransformHelpers.res",
      1,
      58
    ],
    Error: new Error()
  };
}

function deserialize_Belt_HashMapInt____t(a, b) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "TransformHelpers.res",
      3,
      49
    ],
    Error: new Error()
  };
}

function deserialize_Belt__HashMap__Int__t(a, b) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "TransformHelpers.res",
      5,
      50
    ],
    Error: new Error()
  };
}

function serialize_Belt__HashMap__Int__t(a, b) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "TransformHelpers.res",
      9,
      48
    ],
    Error: new Error()
  };
}

function serialize_Belt_HashMapInt____t(transformer, t) {
  throw {
    RE_EXN_ID: "Assert_failure",
    _1: [
      "TransformHelpers.res",
      11,
      57
    ],
    Error: new Error()
  };
}

export {
  deserialize_Belt__HashMapInt__t,
  deserialize_Belt_HashMapInt____t,
  deserialize_Belt__HashMap__Int__t,
  serialize_Belt__HashMap__Int__t,
  serialize_Belt_HashMapInt____t,
}
/* No side effect */
