// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_List from "@rescript/runtime/lib/es6/Stdlib_List.js";
import * as JsxRuntime from "react/jsx-runtime";

let b = [
  1,
  2,
  3,
  12
];

let c = JsxRuntime.jsx("div", {});

function s(prim) {
  return prim;
}

function ZZ$M(props) {
  return props.x;
}

let M = {
  make: ZZ$M
};

let d = JsxRuntime.jsx(ZZ$M, {
  x: "abc"
});

function ZZ$J(props) {
  return null;
}

let J = {
  make: ZZ$J
};

let z = JsxRuntime.jsxs(ZZ$J, {
  children: [
    "",
    ""
  ]
});

let MSig = {
  x: 14
};

let Impl = {
  x: 14
};

let Impl2 = {
  x: 14
};

function testRecordFields(gr) {
  return gr.s;
}

function uncurried(x) {
  return x + 1 | 0;
}

let Inner = {
  vInner: 34
};

function functionWithTypeAnnotation() {
  return 1;
}

function ZZ$HoverInsideModuleWithComponent(props) {
  return null;
}

let HoverInsideModuleWithComponent = {
  x: 2,
  make: ZZ$HoverInsideModuleWithComponent
};

function foo(age, name) {
  return name + age.toString();
}

function next(numberOpt, year) {
  let number = numberOpt !== undefined ? numberOpt : 0;
  return number + year | 0;
}

let Lib = {
  foo: foo,
  next: next
};

function customDouble(foo) {
  return (foo << 1);
}

function customDouble2(foo) {
  return (foo << 1);
}

let Dep = {
  customDouble: customDouble,
  customDouble2: customDouble2
};

function customDouble$1(foo) {
  return (foo << 1);
}

let cc = 22;

function ZZ$O$Comp(props) {
  let __foo = props.foo;
  let __first = props.first;
  let first = __first !== undefined ? __first : "";
  let foo = __foo !== undefined ? __foo : 3;
  return first + props.second + foo.toString();
}

let Comp = {
  make: ZZ$O$Comp
};

let O = {
  Comp: Comp
};

let comp = JsxRuntime.jsx(ZZ$O$Comp, {
  second: "abcc",
  v: 12
}, "12");

let lll = Stdlib_List.make(3, 4);

let arr = [
  1,
  2,
  3
];

let a = 12;

let D;

let E;

let F;

let v1 = "V1";

let DoubleNested;

let valueInner = 34;

let abc = "abc";

let some7 = 7;

export {
  a,
  b,
  c,
  s,
  M,
  d,
  J,
  z,
  MSig,
  Impl,
  Impl2,
  D,
  E,
  F,
  testRecordFields,
  v1,
  DoubleNested,
  uncurried,
  Inner,
  valueInner,
  functionWithTypeAnnotation,
  HoverInsideModuleWithComponent,
  Lib,
  Dep,
  customDouble$1 as customDouble,
  cc,
  O,
  comp,
  lll,
  abc,
  arr,
  some7,
}
/* c Not a pure module */
